### ISSUE TITLE
german Kaldi acoustic model?

### ISSUE THREAD

**Issue by floriq** [gooofy/nlp#1]
Hi Guenter,

I'm using your latest german acoustic model for Sphinx-4 with great success in my ILA - voice assistant! :-) Right now I'm trying to integrate support for Kaldi and I was wondering if you have any plans to make a DNN based model supporting that? I'd be really happy to see that :-)
Thanks for the great work so far!

cu, 
Florian

Btw, if you'd like to see you model in action:
https://sites.google.com/site/ilavoiceassistant/

**Comment by tarekmehrez** [comment]
+1

**Comment by gooofy** [comment]
Hi Florian,

ILA looks very cool to me! actually I am also intending to build a HAL clone at some point in the future, this is how I got started working on the voxforge model. I will definitely check out your project a bit deeper. My personal plan was to go a bit deeper in terms of natural language understanding (i.e. using machine learning, word vectors, grammars, semantics...) but on the other hand keyword/chatbot-like approaches are definitely more practical and lead to faster results like ILA demonstrates quite impressively.

BTW: is ILA open source / free software ?

about kaldi: yes, kaldi is pretty high on my todo list - I read great things about it and I think it could serve as an interesting alternative to pocketsphinx where the necessary compute power is available (so no embedded devices for now). I didn't have time to work on my voxforge model recently (busy with other projects) but I do plan to continue working on it now. 

thanks - and keep up the good work,

   guenter

**Comment by floriq** [comment]
Hi Guenter,

nice to hear that! Please leave me a note when you update anything :-)

ILA is semi-open right now. For the start I wanted to keep the core code under my control while at the same time giving others the possibility to access the most important aspects in an open-source way (custom_interpreter for e.g. own NLU scripts, TTS and STT scripts, Interface for add-ons etc.). You mentioned the NLU part and this is definately something I want to implement in much more detail too. Right now the NLP that is happening after the keyphrase matching is very basic using only combinations of keywords. Maybe we can work together on something! :-)

ty2,
Florian

**Comment by gooofy** [comment]
latest release of my german voxforge model does contain some kaldi models now.
