### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by megaterik** [gooofy/nlp#2]
Hi,

When cloning repository and executing any script I am getting error about speech section not being defined in config. I have also wgetted http://www.repository.voxforge1.org/downloads/fr/Trunk/Audio/Main/16kHz_16bit/ -- I guess this corresponds to "16khzdir" setting, but I am not sure how to export it to database that is required by config.

Is there some tutorial about filling config and populating database somewhere?

Thanks!

**Comment by gooofy** [comment]
Hi Taras,

On Fri, Sep 4, 2015 at 10:54 PM, Taras Klaskovsky
<notifications@github.com> wrote:
>
> Hi,
>
> When cloning repository and executing any script I am getting error about speech section not being defined in config.

here is my ~/.airc to get you started:

[speech]
dbserver  = localhost
dbname    = lexicon_de
dbuser    = lexicon
dbpass    = *******
audiodir  = /home/ai/voxforge/de/audio
contribdir= /home/ai/voxforge/de/audio-contrib
16khzdir  = /home/ai/voxforge/de/16khz
featdir   = /home/ai/voxforge/de/feat
workdir   = /home/ai/voxforge/de/work
lmworkdir = /home/ai/voxforge/de/lm
europarl  = /home/ai/corpora/de/europarl-v7.de-en.de
parole-de = /home/ai/corpora/de/German Parole Corpus/DE_Parole
tiger     = /home/ai/corpora/de/tigercorpus2.1/corpus
vflogin   = guenter
webroot   = /home/guenter/projects/ai/speech/web/html
sentences = /home/ai/sentences/de
psmodel   = /home/guenter/projects/ai/speech/output/phonetisaurus/dict-xsampa.fst
abookdir  = /home/ai/voxforge/de/abook

[pocketsphinx]
hmm       = /home/ai/voxforge/de/work/model_parameters/voxforge.cd_cont_3000
lm        = /home/ai/voxforge/de/work/etc/voxforge.lm.DMP
dict      = /home/ai/voxforge/de/work/etc/voxforge.dic

> I have also wgetted http://www.repository.voxforge1.org/downloads/fr/Trunk/Audio/Main/16kHz_16bit/ -- I guess this corresponds to "16khzdir" setting, but I am not sure how to export it to database that is required by config.

ah, I see you're going to work on the french part of voxforge? very
cool but be advised that this will definitely require some work. you
will most likely want to define new phonemes (my scripts currently
focus on german and english phonemes) and a lot of tokenizer-hacks
will probably not work so great on french input as well.

> Is there some tutorial about filling config and populating database somewhere?

you can find my current DB dump here:

http://goofy.zamia.org/voxforge/de/

it could be worth trying starting from there, emptying all the tables
(so you have a clean database) and work from there. take a look at the
README.md file, this should give you some hints. basically, you need
to import the audio-metadata (audio-import.py), review that and fix
transcripts (audio-transcribe.py) and create/fix the phoneme directory
so it will cover all tokens used in the transcripts (lex-edit.py).
once that is complete you can have your first go at building the model

guenter
