### ISSUE TITLE
cmusphinx audio models from voxforge

### ISSUE THREAD

**Issue by inktrap** [gooofy/nlp#3]
I could not get your voxforge models to work for me (I didn't want to clone the whole nlp repo but did not know how I should contact you otherwise). I created a repository that explains the problem in more detail [here](https://github.com/inktrap/cmusphinx-de). The error when running cmusphinx (with your [cont](https://github.com/inktrap/cmusphinx-de/blob/master/cmusphinx-cont-voxforge-de-r20161117/test.sh) and [ptm](https://github.com/inktrap/cmusphinx-de/blob/master/cmusphinx-ptm-voxforge-de-r20161117/test.sh) models) is (in both cases):

```
... long list of output ...
WARN: "ngram_model_trie.c", line 435: Duplicate word in dictionary: 
ERROR: "ngram_search.c", line 206: Language model/set does not contain </s>, recognition will fail
```

**Comment by gooofy** [comment]
can you try these repackaged files instead?

[https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/German/](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/German/)

**Comment by inktrap** [comment]
So, I guess this issue is solved then.

Just FYI (unrelated to ``nlp``): I am already doing that and currently
asking for help
[here](https://sourceforge.net/p/cmusphinx/discussion/help/thread/289d32e1/)
(perhaps you want to join the discussion there?).

All of this makes [this
announcement](http://cmusphinx.sourceforge.net/2016/09/new-27k-words-70h-german-model-released/)
more confusing: I really had to dig around to find your models in the
first place and now the stable models are the ones that should be used
(are they?).

Excerpts from Guenter Bartsch's message of 2017-01-30 09:06:53 -0800:
> can you try these repackaged files instead?
> 
> [https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/German/](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/German/)
>

**Comment by gooofy** [comment]
glad to hear you got it working despite the state of flux tools and models are in right now.

closing the issue.

**Comment by inktrap** [comment]
Excerpts from Guenter Bartsch's message of 2017-01-30 12:29:13 -0800:
> glad to hear you got it working despite the state of flux tools and models are in right now.
> 
> closing the issue.
> 

Thanks :). Btw. really cool idea to bash-glue an nlp system together.
