### ISSUE TITLE
Update existing model? 

### ISSUE THREAD

**Issue by chief7** [gooofy/nlp#4]
Hi! I was wondering if there's any way to update a model that has already been computed once we get new training data? 
I'm talking about the nnet3 (tdnn) here. I know it's most probably a question for the guys at kaldi but since we have so many useful scripts here I was kind of hoping that I'm not the first one having such an idea... 

Thanks in advance.

**Comment by gooofy** [comment]
sorry, no idea - I always build my models from scratch
